# Site settings
course_name: E1-216 Computer Vision
course_instructor: "Venu Madhav Govindu"
course_instructor_url: "https://ee.iisc.ac.in/~venu/"
course_instructor_phone: "2293 3171"
course_instructor_email: "venug@iisc.ac.in"
course_instructor_email_text: "venug AT iisc DOT ac DOT in"
course_timings: "Mon, Wed: 2-4 PM"
course_semester: "Jan-Apr 2022"
course_ta: "Lalit Manam"
course_ta_email: "lalitmanam@iisc.ac.in"
course_ta_email_text: "lalitmanam AT iisc DOT ac DOT in"


baseurl: "/cviisc" # the subpath of your site, e.g. /blog/
url: "http://lalitmanam.github.io/" # the base hostname & protocol for your site

schoolname: "Indian Institute of Science"
schoolurl: "https://ee.iisc.ac.in/"
# twitter_username: username 

address: |
    Dept. of Electrical Engineering
    Indian Institute of Science
    Bengaluru, Karnataka, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
